'use strict';
const {groups,hints}=require('../services/obfuscationRules');
// Match the accepted client-status icon: 18px SVG, 0.8px ring and 1px symbol.
const infoIcon='<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.333333" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10" stroke-width="1.066667"/><line x1="12" x2="12" y1="12" y2="16"/><line x1="12" x2="12.01" y1="8" y2="8"/></svg>';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderObfuscation(profile) {
  const available=profile.status==='ok'&&profile.protocolVersion==='3.1';
  const fields=groups.map(group=>`<section class="obfuscation-group"><h3>${esc(group.title)}</h3><div class="parameter-grid">${group.names.map(name=>{
    const [description,help]=hints[name];
    const value=profile.clientInterfaceParameters?.[name]??'';
    return `<div class="param obfuscation-param"><div class="obfuscation-label"><label for="obf-${name}">${esc(name)}</label><button class="obfuscation-info" type="button" aria-label="О параметре ${esc(name)}" aria-expanded="false" aria-controls="obf-help-${name}" data-obfuscation-help>${infoIcon}</button></div><input id="obf-${name}" name="${name}" value="${esc(value)}" maxlength="${/^I/.test(name)?4096:128}" autocomplete="off" spellcheck="false" disabled><div class="obfuscation-popover" id="obf-help-${name}" role="note" hidden><strong>${esc(name)}</strong><p>${esc(description)}</p><p>${esc(help)}</p></div></div>`;
  }).join('')}</div></section>`).join('');
  return `<section class="card obfuscation admin-access-card" id="obfuscationCard"><div class="card-head"><div><h2>AWG Obfuscation</h2><p>Параметры маскировки AmneziaWG.</p></div><button class="admin-access-toggle" id="obfuscationToggle" type="button" aria-pressed="false" ${available?'':'disabled'}><span class="admin-access-mode" id="obfuscationMode">Read-only</span><span class="admin-access-switch" aria-hidden="true"></span></button></div><form id="obfuscationForm" novalidate>${available?fields:'<p class="obfuscation-unavailable">Редактирование доступно для работающего AmneziaWG 3.1.</p>'}<div class="obfuscation-actions" hidden><button class="btn purple" id="obfuscationGenerate" type="button">Случайные параметры</button><button class="btn purple" id="obfuscationSave" type="submit">Сохранить</button><p class="obfuscation-warning">Изменение общих параметров потребует обновления конфигов на устройствах. Если панель открыта через этот VPN, связь с ней может оборваться. Держите отдельный доступ к серверу.</p></div><p class="obfuscation-feedback" id="obfuscationStatus" role="status" aria-live="polite"></p></form></section><div class="modal-backdrop" id="obfuscationModal" aria-hidden="true"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="obfuscationModalTitle"><div class="card-head"><div><h2 id="obfuscationModalTitle">Изменить обфускацию?</h2><p>Изменения коснутся всей VPN-ноды.</p></div><button class="modal-close" type="button" data-close-modal aria-label="Закрыть">×</button></div><div class="modal-body backup-fields"><p id="obfuscationImpact"></p><p class="backup-warning">При изменении общих параметров скачайте и раздайте обновлённые конфиги или QR-коды. Ключи и адреса клиентов не меняются. Прежние файлы на устройствах автоматически не обновятся.</p><p class="backup-warning">Для клиентов без сохранённого конфига нужен исходный .conf и его обновление вручную либо новый доступ. Убедитесь, что у вас есть доступ к панели и SSH вне этого VPN.</p><label class="backup-encrypt-option"><input type="checkbox" id="obfuscationConfirmConsent">Я понимаю последствия для клиентов</label><p class="access-error" id="obfuscationError" role="alert" hidden></p></div><div class="modal-actions"><button class="btn" type="button" data-close-modal>Отмена</button><button class="btn purple" id="obfuscationApply" type="button" disabled>Применить</button></div></div></div>`;
}
module.exports={renderObfuscation};
